import * as esbuild from 'esbuild';
import { existsSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes('--watch');

// --- Auto-detect diplomacy plugin ---
const diplomacyRoot = resolve(__dirname, '../uncivilised-diplomacy');
const diplomacyPlugin = resolve(diplomacyRoot, 'src/plugin.js');
const hasDiplomacy = existsSync(diplomacyPlugin);

const genFile = resolve(__dirname, 'src/_diplomacy-plugin.gen.js');
if (hasDiplomacy) {
  console.log('Diplomacy module detected at', diplomacyRoot);
  writeFileSync(genFile,
    `// Auto-generated by esbuild.config.mjs — do not edit\n` +
    `import { init } from '${diplomacyPlugin.replace(/\\/g, '/')}';\n` +
    `import { registerDiplomacyPlugin } from './diplomacy-api.js';\n` +
    `init(registerDiplomacyPlugin);\n`
  );
} else {
  console.log('Diplomacy module not found — building without it');
  writeFileSync(genFile,
    `// Auto-generated by esbuild.config.mjs — do not edit\n` +
    `// Diplomacy plugin not detected. Game running in open-source mode.\n`
  );
}

// --- esbuild alias: @game/* resolves to src/* (used by diplomacy plugin) ---
const alias = hasDiplomacy ? {
  '@game/constants.js': resolve(__dirname, 'src/constants.js'),
  '@game/state.js': resolve(__dirname, 'src/state.js'),
  '@game/hex.js': resolve(__dirname, 'src/hex.js'),
  '@game/events.js': resolve(__dirname, 'src/events.js'),
  '@game/render.js': resolve(__dirname, 'src/render.js'),
  '@game/map.js': resolve(__dirname, 'src/map.js'),
  '@game/units.js': resolve(__dirname, 'src/units.js'),
  '@game/discovery.js': resolve(__dirname, 'src/discovery.js'),
  '@game/leaderboard.js': resolve(__dirname, 'src/leaderboard.js'),
  '@game/combat.js': resolve(__dirname, 'src/combat.js'),
  '@game/input.js': resolve(__dirname, 'src/input.js'),
} : {};

const config = {
  entryPoints: ['src/main.js'],
  bundle: true,
  outfile: 'game.js',
  format: 'iife',
  target: ['es2020'],
  sourcemap: true,
  alias,
  banner: {
    js: `/*
 * UNCIVILISED — The Ancient Era
 * Built from src/ modules via esbuild
 */`,
  },
};

if (isWatch) {
  const context = await esbuild.context(config);
  await context.watch();
  console.log('Watching for changes...');
} else {
  await esbuild.build(config);
  console.log('Build complete: game.js');
}
